name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: test
        run: npm run test
      - uses: akhileshns/heroku-deploy@v3.12.12
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "enigmatic-brushlands-75826"
          heroku_email: "niko.o.ruohonen@gmail.com"
          healthcheck: "https://enigmatic-brushlands-75826.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true      
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
       
       - name: Test Success
            uses: rjstone/discord-webhook-notify@v1.0.4
            if: success()
            with:
                severity: info
                details: Test Succeeded!
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        - name: Test Failure
            uses: rjstone/discord-webhook-notify@v1.0.4
            if: failure()
            with:
                severity: error
                details: Test Failed!
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
        - name: Test Cancelled
            uses: rjstone/discord-webhook-notify@v1.0.4
            if: cancelled()
            with:
                severity: warn
                details: Test Cancelled!
                webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}